name: 'nyc_trips_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_trips_analytics:
    +materialized: table  # default materialization
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold

seeds:
  +schema: seed_data